# Generated by Django 5.0.7 on 2024-08-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookdetails', '0002_category_alter_bookdetails_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdetails',
            name='book_picture',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
