# Generated by Django 5.0.7 on 2024-08-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookdetails', '0003_bookdetails_book_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdetails',
            name='book_picture',
            field=models.ImageField(upload_to='book_image/'),
        ),
    ]
