# Generated by Django 5.0.7 on 2024-09-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookdetails', '0007_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdetails',
            name='book_id',
            field=models.AutoField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
