# Generated by Django 5.0.7 on 2024-09-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookdetails', '0008_alter_bookdetails_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdetails',
            name='book_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='book',
            table='bookdetails_book',
        ),
        migrations.AlterModelTable(
            name='bookdetails',
            table='bookdetails_bookdetails',
        ),
        migrations.AlterModelTable(
            name='review',
            table='bookdetails_review',
        ),
        migrations.AlterModelTable(
            name='wishlist',
            table='bookdetails_wishlist',
        ),
    ]
